### PR TITLE
Fix #139. `presence` messages were backwards.

### LINKED ISSUE #139: `presence` messages are backwards
## Version

Starts with [this commit](https://github.com/DockYard/ember-changeset-validations/commit/7f29668f8d39246e54f1ce4bb7f5b30a443a6812) in latest master

## Expected Behavior

When using `presence(true)` I expect the message to say `{key} can't be blank`.

When using `buildMessage('present')` I expect `{key} can't be blank`.
When using `buildMessage('blank')` I expect `{key} must be blank`.

## Actual Behavior

When using `presence(true)` the message says`{key} must be blank`.
On [these lines](https://github.com/DockYard/ember-changeset-validations/blob/master/addon/validators/presence.js#L17-L21) the `type` that is returned when the value is blank is `blank`. In the new mapping `blank` points to the correct message. However, the logic flips the type to `present` which is the wrong message.

When using `buildMessage('present')` I get `{key} must be blank`.
When using `buildMessage('blank')` I get `{key} can't be blank`.

### PR DESCRIPTION
**Pull request by brandynbennett**
`buildMessage('present')` was returning `{key} must be blank` instead
of `{key} can't be blank`.

`buildMessage('blank')` was returning `{key} can't be blank` instead
of `{key} must be blank`.

Closes #139

### CODE REVIEW

**Comment by jamesdixon** [comment]
LGTM 😸

**Comment by poteto** [comment]
Could you open a PR in `ember-validators` instead? I would like validation logic to live there (it's a shared core addon with `ember-cp-validations`), so any fixes in that addon will benefit both addons.

**Comment by brandynbennett** [comment]
@poteto That makes sense. Are the backwards messages happening in `ember-cp-validations` as well? Do you think it makes sense to simply switch the messages back to the way they were before? That would be a backward incompatible change for `ember-validators` and would require a major version bump.

**Comment by bkl1989** [comment]
@poteto Is this going to be resolved in ember-validators at any point? Can you explain how this is their issue rather than an ember-changeset-validations issue? Ember-changeset-validations is a dependency within a dependency for me, so I don't have the option to create a fork to fix it in the interim.

**Comment by kbbpartners** [comment]
PR opened here: https://github.com/offirgolan/ember-validators/pull/51

Couldn't figure out how to run the tests, and ember-validators seems to be a bit neglected in general. 

FWIW, we're going to use a similar fork/fix to @brandynbennett until this user-facing bug gets some love.

**Comment by offirgolan** [comment]
@kbbpartners `ember-validators` is definitely not being neglected. You should be able to run the tests via `npm install && bower install && ember test`.

@poteto Im sorry for the confusion behind this issue. I think the best course of action would be to make the change in this repo instead since merging @kbbpartners PR would have to result in a major version bump to ember-validations + all upstream dependents. 

A simple change here can solve this problem:

```
// addon/utils/messages,js

export default assign(Messages, {
  getDescriptionFor(key = '') {
    return capitalize(dasherize(key).split(/[_-]/g).join(' '));
  },
  
  blank: Messages.presence,
  presence: Messages.blank
});
```

Doing this can also remove the weird logic implemented in `validators/presence.js`.

Thoughts?

**Comment by offirgolan** [comment]
If so, I can open a quick PR to resolve this issue 😄

**Comment by kbbpartners** [comment]
@offirgolan Apologies, and thanks for stepping in. I got the tests running, but I can understand why you'd prefer to avoid a breaking change.

File: addon/validators/presence.js [hunk 1]
```diff
@@ -12,7 +12,6 @@ export default function validatePresence(options) {
     if (typeof result === 'boolean' || typeof result === 'string') {
       return result;
     } else {
-
       // We flipped the meaning behind `present` and `blank` so switch the two
       if (result.type === 'present') {
```
Comment (offirgolan) [inline addon/validators/presence.js]: @brandynbennett you should be able to remove this entire block now.

**Comment by offirgolan** [comment]
@kbbpartners no worries at all 😄 . I will keep your PR open on ember-validators as a reminder to be merged in for next time I do a bigger release.

File: addon/validators/presence.js (hunk 1 above)
Comment (brandynbennett) [inline addon/validators/presence.js]: What do I need to do to remove this block? When I remove it the tests fail.

Comment (offirgolan) [inline addon/validators/presence.js]: That's weird. This just flips the two error messages programatically... There shouldnt be a need for this anymore. 

I think the tests fail because its checking for the `type` not the actual error message itself. Can you verify?

File: addon/utils/messages.js [hunk 2]
```diff
@@ -9,6 +9,10 @@ const assign = Ember.assign || Ember.merge;
 const Messages = assign({}, _Messages);
 
 export default assign(Messages, {
+  // Blank and present are flipped in ember-validators. Need to flip them back here
+  blank: '{description} must be blank',
+  present: '{description} can\'t be blank',
```
Comment (offirgolan) [inline addon/utils/messages.js]: I suggest doing the following:

```js
blank: _Messages.present,
present: _Messages.blank
```

That way if the error messages do change in the future, we wouldnt have to go back and change it here too.

File: addon/validators/presence.js (hunk 1 above)
Comment (brandynbennett) [inline addon/validators/presence.js]: No the actual error messages are coming back flip. Some of the tests are looking at the the changeset errors object and the messages are flipped.

Comment (offirgolan) [inline addon/validators/presence.js]: Oh right... that actually makes sense. Thanks for verifying 😄

**Comment by Kuzirashi** [comment]
Hey, first of all - addon is great, but 2 months and this basic fix for fundamental issue is not merged? : P

**Comment by brandynbennett** [comment]
@poteto Can this be merged?

**Comment by poteto** [comment]
Rerunning tests

**Comment by jamesdixon** [comment]
Hi all, any chance a new version will be released to NPM soon that contains this fix?

**Comment by jamesdixon** [comment]
@poteto thanks!
